spring:
  application:
    name: picpay-api-gateway
  cloud:
    gateway:
      routes:
        - id: wallet-service
          uri: http://localhost:8081/
          predicates:
            - Path=/picpay-wallet/**
        - id: movement-service
          uri: http://localhost:8082/
          predicates:
            - Path=/picpay-movement/**
        - id: timeline-service
          uri: http://localhost:8083/
          predicates:
            - Path=/picpay-timeline/**

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost

server:
  port: 8080
