server:
  port: 8081
  servlet:
    context-path: '/picpay-wallet/'
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: picpay-wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db-wallet
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          max-interval: 3000
logging:
  level:
    com.picpay: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

picpay:
  api:
    url:
      movement: 'http://picpay-movement-service'
      timeline: 'http://picpay-timeline-service'
  broker:
    exchange:
      movementEvent: picpay.movementevent
      dlqExchange: picpay.dlq
    queue:
      amountEventQueue:
        dlq: dlq.updateamount
        name: picpay.movementevent.ms.wallet.updateamount
    key:
      paymentKey: ms.movement.payment
      bankTransferKey: ms.movement.banktransfer
      updateAmountKey: ms.wallet.updateamount
      timelineKey: ms.timeline.newtimeline

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost