version: '2'
services:
  postgresql:
    extends:
      file: postgresql.yaml
      service: postgresql
    container_name: postgresql
  elasticsearch:
    extends:
      file: elasticsearch.yaml
      service: elasticsearch
    container_name: elasticsearch