version: '7.6.2'
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx1024m"
      - "discovery.type=single-node"