version: '11.5'
services:
  postgresql:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql